import { main, header, footer } from './app.js';

export function connexion()
{
	const navElement = document.createElement('nav');
	navElement.classList.add('navbar', 'navbar-expand-lg', 'navbar-light', 'bg-light');
	const containerElement = document.createElement('div');
	containerElement.classList.add('container');
	const brandElement = document.createElement('a');
	brandElement.classList.add('navbar-brand');
	brandElement.href = '/';
	brandElement.textContent = 'Transcendance';
	const buttonElement = document.createElement('button');
	buttonElement.classList.add('navbar-toggler');
	buttonElement.type = 'button';
	buttonElement.setAttribute('data-bs-toggle', 'collapse');
	buttonElement.setAttribute('data-bs-target', '#navbarNav');
	buttonElement.setAttribute('aria-controls', 'navbarNav');
	buttonElement.setAttribute('aria-expanded', 'false');
	buttonElement.setAttribute('aria-label', 'Toggle navigation');
	const spanElement = document.createElement('span');
	spanElement.classList.add('navbar-toggler-icon');
	buttonElement.appendChild(spanElement);
	containerElement.appendChild(brandElement);
	containerElement.appendChild(buttonElement);
	navElement.appendChild(containerElement);
	header.appendChild(navElement);

	const formElement = document.createElement('div');
	formElement.classList.add('Form');
	formElement.id = 'connexion';
	const form = document.createElement('form');
	const h1Element = document.createElement('h1');
	h1Element.textContent = 'Connexion';
	const emailLabelElement = document.createElement('label');
	emailLabelElement.classList.add('form-label');
	emailLabelElement.setAttribute('for', 'exampleInputEmail1');
	emailLabelElement.textContent = 'Email address';
	const emailInputElement = document.createElement('input');
	emailInputElement.classList.add('form-control');
	emailInputElement.type = 'email';
	emailInputElement.id = 'exampleInputEmail1';
	const emailHelpElement = document.createElement('div');
	emailHelpElement.classList.add('form-text');
	emailHelpElement.id = 'emailHelp';
	emailHelpElement.textContent = "We'll never share your email with anyone else.";
	const passwordLabelElement = document.createElement('label');
	passwordLabelElement.classList.add('form-label');
	passwordLabelElement.setAttribute('for', 'exampleInputPassword1');
	passwordLabelElement.textContent = 'Password';
	const passwordInputElement = document.createElement('input');
	passwordInputElement.classList.add('form-control');
	passwordInputElement.type = 'password';
	passwordInputElement.id = 'exampleInputPassword1';
	const centerElement = document.createElement('center');
	const submitButtonElement = document.createElement('button');
	submitButtonElement.classList.add('btn', 'btn-success');
	submitButtonElement.type = 'submit';
	submitButtonElement.textContent = 'Connexion';
	const registerButtonElement = document.createElement('button');
	registerButtonElement.classList.add('btn', 'btn-primary');
	registerButtonElement.type = 'submit';
	registerButtonElement.textContent = 'Inscription';
	const brElement = document.createElement('br');
	const secondaryButtonElement = document.createElement('button');
	secondaryButtonElement.classList.add('btn', 'btn-secondary');
	secondaryButtonElement.type = 'submit';
	secondaryButtonElement.textContent = 'Connexion avec 42';
	
	centerElement.appendChild(submitButtonElement);
	centerElement.appendChild(registerButtonElement);
	centerElement.appendChild(brElement);
	centerElement.appendChild(secondaryButtonElement);
	form.appendChild(h1Element);
	form.appendChild(emailLabelElement);
	form.appendChild(emailInputElement);
	form.appendChild(emailHelpElement);
	form.appendChild(passwordLabelElement);
	form.appendChild(passwordInputElement);
	form.appendChild(centerElement);
	formElement.appendChild(form);
	main.appendChild(formElement);
	
	footer.style.position = 'absolute';
	footer.style.bottom = '0';
	const pElement = document.createElement('p');
	pElement.textContent = 'ft_transcendance - 42';
	footer.appendChild(pElement);
}