version: '3'
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - imgs:/var/www
      - ./srcs/db/create_tables.sql:/tmp/create_tables.sql
      - ./srcs/db/create_data.sql:/tmp/create_data.sql
      - ./srcs/db/set_database.sh:/docker-entrypoint-initdb.d/set_database.sh
    env_file:
      - .env

  web:
    container_name: django
    build:
      context: ./srcs/web
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - web:/app/django
      - imgs:/var/www/imgs/
      - staticfiles:/var/www/static/
    env_file:
      - .env

  nginx:
    container_name: nginx
    build:
      context: ./srcs/nginx
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - web
    ports:
      - "0.0.0.0:8080:443"
    volumes:
      - staticfiles:/var/www/static/
      - ./srcs/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - .env

volumes:
  imgs:
    driver: local
    driver_opts:
      type: none
      device: ./srcs/db/imgs
      o: bind
  web:
    driver: local
    driver_opts:
      type: none
      device: ./srcs/web/app
      o: bind
  staticfiles:
    driver: local
